# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", ENV.fetch("DB_HOST", "localhost")) %>
  port: <%= ENV.fetch("PGPORT", ENV.fetch("DB_PORT", "5432")) %>
  username: <%= ENV.fetch("PGUSER", ENV.fetch("DB_USERNAME", "postgres")) %>
  password: <%= ENV.fetch("PGPASSWORD", ENV.fetch("DB_PASSWORD", "")) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "forum_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "forum_test") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("PGDATABASE", ENV.fetch("DB_NAME", "forum_production")) %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("PGDATABASE", ENV.fetch("DB_NAME", "forum_production")) %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("PGDATABASE", ENV.fetch("DB_NAME", "forum_production")) %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("PGDATABASE", ENV.fetch("DB_NAME", "forum_production")) %>
    migrations_paths: db/cable_migrate
